### ISSUE TITLE
Media in DMs is nil

### ISSUE THREAD

**Issue by Touexe** [Davincible/goinsta#13]
i'm sure i have sent a picture in dm, i tried fetching dms to see if i can save the picture in dm but i couldn't get anything since media field in InboxItem struct is nil 

result: 

`&{ID:30179181517345856745445460340113408 UserID:50228679252 Timestamp:1636016708247038 ClientContext:6861951351702761258 IsShhMode:false TqSeqID:0 Type:media Text: Like: Reel:<nil> Media:<nil> ActionLog:<nil> Link:{Text: Context:{Url: Title: Summary: ImageUrl:}}}`

what could be wrong anyway?

**Comment by Davincible** [comment]
Thanks for reporting, I'll investigate it

**Comment by Touexe** [comment]
@Davincible any update on this?

**Comment by Davincible** [comment]
Harvey had the time yet. Will try to make time for it this weekend :)

**Comment by Touexe** [comment]
@Davincible thanks take your time....

**Comment by Davincible** [comment]
The cause of your issue is a json property reference mismatch. Here:
https://github.com/Davincible/goinsta/blob/172c4b597032ba02bc1bd4c51dd2fd5041b677b2/inbox.go#L111
It should be:
```
Media               *Item      `json:"media"`
MediaShare     *Item      `json:"media_share"`
```
Where `Media` represents directly shared media, and `MediaShare` represents shared media.

I need to iron out some other bugs with DMs not showing up in the data struct before I push the commit

**Comment by Davincible** [comment]
Its pushed!

See:
https://github.com/Davincible/goinsta/releases/tag/v3.0.4

**Comment by Touexe** [comment]
@Davincible thank you so much! it works like charm for media type message, I'm able to get item struct of the media. However, is there anyway to have the same thing for voice_media type and raven_media? Media field is nil when the message is voice_media or raven_media. Or is it not possible by the api itself?

**Comment by Davincible** [comment]
Ahh it should be possible, but haven't encountered them yet. What is raven media exactly? I'll play around with the voice message one

**Comment by Davincible** [comment]
Added voice message compatibility, check the latest commit

**Comment by Davincible** [comment]
From what, I could see raven_media has visual_media. Added that

**Comment by Touexe** [comment]
thanks u're pretty fast! thanks for being so active. voice message works like charm. But we don't seem to be able to get media url or bytes from raven_media? it's view once message or repalyable message

**Comment by Davincible** [comment]
Check again :)

**Comment by Touexe** [comment]
thanks it all work now! closing...
