### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by Verx1713** [Davincible/goinsta#15]
### Typo location
Page: [3. Profiles & Users](https://github.com/Davincible/goinsta/wiki/3.-Profiles-&-Users#profiles)
Section: Below "The Profiles struct has three main methods" sentence, in code block third line
### Typo
`user, err := insta.Profile.ByName("f1")`
### Correction
`user, err := insta.Profiles.ByName("f1")`

**Comment by Davincible** [comment]
Thanks for reporting, will change it soon

**Comment by Davincible** [comment]
Changed
