### ISSUE TITLE
Accept pending friendships

### ISSUE THREAD

**Issue by dnsbty** [Davincible/goinsta#19]
I want to be able to accept and ignore pending friendships, and I can't find a function to be able to do that anywhere in the documentation. I would be happy to contribute this in a PR, but I don't really know how to look at the requests the Android app makes. On the web though, it's with this endpoint:

```
POST https://www.instagram.com/web/friendships/{user_pk}/approve/
POST https://www.instagram.com/web/friendships/{user_pk}/ignore/
```

If trying to replicate in the app, you would have to have two accounts. One of them would need to be set to private, then the second would need to request to follow the private account. Then from the private account you would have a notification in your feed about the new request, and you could then accept or reject it there.

**Comment by Davincible** [comment]
You're right, this hasn't been implemented yet. Thanks for the request. I will look at it this week!

**Comment by Davincible** [comment]
Sorry for the delay, but this has now been implemented!

Check [account_test.go](https://github.com/Davincible/goinsta/blob/master/tests/account_test.go) for an example.

**Comment by dnsbty** [comment]
Thanks for taking this on! I really appreciate it.
