### ISSUE TITLE
Fix bug null pointer doRequest

### ISSUE THREAD

**Issue by BruAPAHE** [Davincible/goinsta#2]
Hello. Please fix bug on https://github.com/Davincible/goinsta/blob/master/request.go#L209
If err !=nil when request struct is nil.

`

        resp, err := insta.c.Do(req)
	if err != nil {
		return nil, nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, nil, fmt.Errorf(
			"Status: '%s', Status Code: '%d', Err: '%v'",
			resp.Status,
			resp.StatusCode,
			err,
		)
	}
`

**Comment by Davincible** [comment]
Fixed. When did you encounter this error though? What did you call?

**Comment by BruAPAHE** [comment]
@Davincible 
`insta := goinsta.New("login", "pass")

	if err := insta.SetProxy("//ip:port", false, false); err != nil {
		log.Fatalln(err)
	}
	if err := insta.Login(); err !=nil{
		log.Fatalln(err)
	}`
