### ISSUE TITLE
login with 2fa otp auth

### ISSUE THREAD

**Issue by vtolstov** [Davincible/goinsta#20]
My account have 2fa enabled via google authenticator. 
How can i login with this lib in this case (i can generate 2fa code via go package based on secret)

**Comment by Davincible** [comment]
Haven't looked at that yet, will put it on the todo!

**Comment by Davincible** [comment]
I have updated the wiki with the following example:
```go
...

err := insta.Login()
if err == goinsta.Err2FA {
  err2FA := insta.TwoFactorInfo.Login2FA(code)
  if err2FA != nil {
    ...
  }
} else if err != nil {
  ...
}
```
Can you let me know if this works for you?

Also, which go package do you use to generate the 2FA code?
