### ISSUE TITLE
Number of comments is always 0

### ISSUE THREAD

**Issue by Nonoleg17** [Davincible/goinsta#25]
Hi, I'm testing the collection of posts on instagram and there was a problem that there are no comments when executing func Next in media.go. 
![image](https://user-images.githubusercontent.com/65135277/164257280-304934be-b200-4365-8509-59cf6d6c23d1.png)
Any ideas how to solve the problem?

**Comment by Davincible** [comment]
Could you be a bit more specific or show some code? What are you running exactly?

**Comment by Nonoleg17** [comment]
Using the Next() function, I get posts
![изображение](https://user-images.githubusercontent.com/65135277/164403247-5aaf0144-fd9e-4a06-a927-e1e6ddba421f.png)
In it I check the answer(body)
![изображение](https://user-images.githubusercontent.com/65135277/164403514-b9916462-5648-4033-95e3-a9e329bcbb48.png)
I attach a file with the answer (I watched Elon Musk's account)
[test.txt](https://github.com/Davincible/goinsta/files/8528746/test.txt)
.

**Comment by Davincible** [comment]
Turns out Instagram changed their API a bit, they don't return the comment count anymore on the feed endpoint, but added a new endpoint.

Inside your for loop, add this function call:
```go
		if err := feed.GetCommentInfo(); err != nil {
			panic(err)
		}

		for _, post := range feed.Latest() {
			fmt.Printf("%d comments found\n", post.CommentInfo.CommentCount)
		}
```

The newly added comment info struct:
```go
type CommentInfo struct {
	LikesEnabled                   bool          `json:"comment_likes_enabled"`
	ThreadingEnabled               bool          `json:"comment_threading_enabled"`
	HasMore                        bool          `json:"has_more_comments"`
	MaxNumVisiblePreview           int           `json:"max_num_visible_preview_comments"`
	PreviewComments                []interface{} `json:"preview_comments"`
	CanViewMorePreview             bool          `json:"can_view_more_preview_comments"`
	CommentCount                   int           `json:"comment_count"`
	HideViewAllCommentEntrypoint   bool          `json:"hide_view_all_comment_entrypoint"`
	InlineComposerDisplayCondition string        `json:"inline_composer_display_condition"`
	InlineComposerImpTriggerTime   int           `json:"inline_composer_imp_trigger_time"`
}

```

Let me know if this works for you

**Comment by Nonoleg17** [comment]
Thanks, it works.
