### ISSUE TITLE
Error logout (405 method not allow) 

### ISSUE THREAD

**Issue by madwolf96** [Davincible/goinsta#30]
Hi, I appreciate your hard work in making this wonderful repo. There is a problem with the logout method.
I am able to face this issue when calling logout
`Error while calling accounts/logout/, status code 405:  (405 Method Not Allowed)`

Can you please have a look at this?

**Comment by Davincible** [comment]
Thanks for letting me know, will do!

**Comment by Davincible** [comment]
Fixed in the latest release
