### ISSUE TITLE
Instagram request payload changed

### ISSUE THREAD

**Issue by FredericoBender** [Davincible/goinsta#32]
The Next() Function that iterate the data from the Posts of a Search() is not working anymore, I think that the request  to instagram have changed, I did the request using a Web browser, so you can see some differences from your code project!
When I run the following code snippet, the results are repeating each Next() command, the pagination does not working anymore!
take a look in the results i have parsing the data to a json File, is repeating the Data 

![image](https://user-images.githubusercontent.com/40170724/189763581-bd67e0bf-408f-40c6-a06a-c29a71aec074.png)

![image](https://user-images.githubusercontent.com/40170724/189763940-84f69964-9564-437f-bf87-f4ad30525ed0.png)
[data.txt](https://github.com/Davincible/goinsta/files/9552036/data.txt)

**Comment by Davincible** [comment]
Hmm thanks for letting me know. Could you paste a code snippet that replicates the issue, so I can check it?

**Comment by FredericoBender** [comment]
I'm made a sample code for you, check that the results are repeated! The same post in each page !  obs: change the extension of the txt file to .go, github don't support go files here
[main.txt](https://github.com/Davincible/goinsta/files/9552108/main.txt)

**Comment by Davincible** [comment]
Thanks for the snippet, I see what you mean! I will soon work on fixing it.

I've also updated your comment to include the code snippet.
You can include code snippets directly in your comments with backticks like this

\```go (whatever language)

... some code ...

\```

**Comment by Davincible** [comment]
Turns out it was a bug on my side. Fixed in the latest commit! Just update your project to the latest version (v3.2.2) and it should work.
