### ISSUE TITLE
Uploading multiple Photos to one Post

### ISSUE THREAD

**Issue by Freccia** [Davincible/goinsta#36]
Would it be possible to upload several photos to one post ?

Something like that:

```
  // Upload Photo
  item, err := insta.Upload(
    &goinsta.UploadOptions{
      File1:     f1,
      File2:     f2,
      File3:     f2,
      File4:     f2,
      Caption:  "multiple photos post",
    },
  )
```

**Comment by JB-BERRY** [comment]
Up

**Comment by JB-BERRY** [comment]
Could you share code for upload an album in a local folder ? Also it is possible to specify a filter on the album ?

thanks a lot for your work
JB

**Comment by Davincible** [comment]
For local photos you just need to read in the file, you can find out how to do that by googling "go read file", you can then pass the bytes into a new buffer, and into the album.


Filters are not possible. On Instagram this does not happen on the server, but on the app. So the api only uploads picture with the filter already applied on it on your phone.

**Comment by JB-BERRY** [comment]
Sorry, I am very bad at golang..
It would really help if you could send me directly the code.
Thanks in advance,
JB

**Comment by Davincible** [comment]
https://gobyexample.com/reading-files
