### ISSUE TITLE
Cannot unmarshal string into Go struct field User.recent.user.fbid_v2 of type int64

### ISSUE THREAD

**Issue by kttyt** [Davincible/goinsta#42]
VisitProfile method started returning an error a couple of hours ago, the api may have changed

**Comment by Subi** [comment]
what error has it been returning , also are you having any issues with `insta.Login` , i've noticed it's starting to just hang

**Comment by kttyt** [comment]
Sorry, didn't paste full error, there it is:
`Failed to get search history: json: cannot unmarshal string into Go struct field User.recent.user.fbid_v2 of type int64`
And no, I didn't notice problem with insta.Login, but in common cases I use insta.Import instead of Login

**Comment by sandheepp** [comment]
I have also faced this issue with User Data Model

**Comment by sandheepp** [comment]
https://github.com/Davincible/goinsta/pull/43
This is working for me

**Comment by kttyt** [comment]
> #43 This is working for me

works for me too

**Comment by Davincible** [comment]
@kttyt is the issue fully resolved now?

**Comment by kttyt** [comment]
> @kttyt is the issue fully resolved now?
yes, it's resolved
