### ISSUE TITLE
question: can I read DMs with Goinsta?

### ISSUE THREAD

**Issue by hadifarnoud** [Davincible/goinsta#5]
I want to accept DM requests and auto reply to them. is there an API for that? did not find any in wiki

**Comment by Davincible** [comment]
@hadifarnoud I don't recall working on a dm request endpoint. I'll look into it!

**Comment by Davincible** [comment]
@hadifarnoud Just added this. You can now do it like this
```
inbox := insta.Inbox

// This will populate inbox.Pending, which is the same as inbox.Conversations, but only contains pending DMs
inbox.SyncPending()
c := inbox.Pending[0]
c.Approve()
c.Send("Hi!")
```

**Comment by hadifarnoud** [comment]
awesome! thank you
