### ISSUE TITLE
Cannot unmarshal array into Go struct field SearchResult.clear_client_cache of type bool exit status 1

### ISSUE THREAD

**Issue by wbdb** [Davincible/goinsta#54]
Sometimes I get this error message:

https://github.com/Davincible/goinsta/blob/9cdb8e46417dbcbfd8bc98c07a5be8d447ea0ffb/search.go#L56

> cannot unmarshal array into Go struct field SearchResult.clear_client_cache of type bool exit status 1

```
followers := profile.User.Followers("")
for followers.Next()  {
	for _, follower := range followers.Users {
	}
}
```

**What I noticed in the Debug Mode JSON:**

There are some typos in the JSON data, such as "proofile_pic_url" instead of "profile_pic_url" and "is_privatee" instead of "is_private". Each occurring once.

```
\"is_privatee\":false,\"
\"proofile_pic_url\":
```

**Steps to reproduce:**

`_, err = insta.VisitProfile("armin_laschet")`

Error: search.go Line 403

**Comment by wbdb** [comment]
Edit search.go to:
`ClearClientCache interface{} `json:"clear_client_cache"``

**Comment by Davincible** [comment]
Thanks for the research, why did you close the PR?

**Comment by wbdb** [comment]
@Davincible That was the Github automatism. I thought it stays open even if I merge and close the branch in the fork. I resent the PR.

**Comment by FrauElster** [comment]
Can you make a new release with this change. The current release is v3.2.6 is almost 10 months old and this change solves a breaking bug. 

Thanks in advance :)

**Comment by FrauElster** [comment]
This still is an issue in v3.2.6. Thought as a reminder :)

**Comment by FrauElster** [comment]
> Can you make a new release with this change. The current release is v3.2.6 is almost 10 months old and this change solves a breaking bug.
> 
> Thanks in advance :)

Just as a reminder, the last release is now a year behind.
