### ISSUE TITLE
Sync to get FollowedBy

### ISSUE THREAD

**Issue by tcurdt** [Davincible/goinsta#6]
Shouldn't the `Sync` update the `FollowedBy`. Seems to be always `false` for me.
```
    following := user.Following()
    for following.Next() {
      for _, f := range following.Users {
        err := f.Sync()
        if err != nil {
          logger.Printf("user=%s err=%s\n", f.Username, err)
        } else {
          logger.Printf("user=%s following=%v\n", f.Username, f.Friendship.FollowedBy)
        }
      }
    }
```

**Comment by Davincible** [comment]
@tcurdt `Sync` only updates things like profile pic and bio etc. To get followers/following you need to call the specified endpoints. You can see it as, if you click on a profile in the insta app, you also still need to click the followers button to view a users followers, which makes the request to fetch all the followers.

Although I do notice now it does not update the initial user struct as you are printing them out in your example, which I should update then.

https://github.com/Davincible/goinsta/blob/d2393696f67f7ebff7465a18207833c663eda5b3/users.go#L311-L333

**Comment by Davincible** [comment]
@tcurdt I've just reinspected the requests the app makes when fetching the following list, and unfortunately, the `FollowedBy` field is not present. This means you have to fetch the profile info/friendship for each account individually to get this field. As such, if you want to get this information for a lot of profiles, an equal amount of requests has to be made at the minimum, so be careful with the request rates if you end up doing this.

**Comment by tcurdt** [comment]
That's a bummer. OK. Thanks for looking into that. 
Do you happen to know what the current request limits are?

**Comment by tcurdt** [comment]
Hm. This is still giving me `false`

    following := user.Following()
    for following.Next() {
      for _, f := range following.Users {

        logger.Printf("[%s] lookup\n", f.Username)
        u, err := insta.Profiles.ByName(f.Username)
        if err != nil {
          return
        }

        logger.Printf("[%s] following=%v followedby=%v\n", u.Username, u.Friendship.Following, u.Friendship.FollowedBy)

        randomizedSleep(1000*15)
      }
      randomizedSleep(millis)
    }

**Comment by Davincible** [comment]
@tcurdt  Yes, because `ByName` or `ByID` return a default user struct with minimal information (profile pic, bio etc.), you'd need to manually call extra methods to fetch either posts, or the friendship. In this case call `user.GetFriendship()`. You can call this directly after `ByName` without delay.

**Comment by tcurdt** [comment]
Seems like the profile lookup is not even required. This here seems to do the job.

    following := user.Following()
    for following.Next() {
      for _, f := range following.Users {

        fs, err := f.GetFriendship()
        if err != nil {
          return
        }

        logger.Printf("[%s] following=%v followedby=%v\n", f.Username, fs.Following, fs.FollowedBy)

        randomizedSleep(1000*15)
      }
      randomizedSleep(millis)
    }

Which kind of makes sense. Just to leave this here.
Thanks for the help! ...and the fact that you are maintaining a fork!
